In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('housing.csv')
df

Sq_Ft  Bedrooms  Bathrooms  Age          Price
0     3232         3          2   27  682777.150273
1     3107         4          3   14  712702.672025
2     2153         1          2   32  442952.288185
3     3764         3          3   22  766553.098528
4     1533         5          3   34  475021.303311
..     ...       ...        ...  ...            ...
995   2954         4          2   25  639568.713751
996   3225         3          2    3  676448.647926
997   1042         3          1   11  343628.053354
998   2299         2          2   35  482083.089811
999    739         3          3   25  311502.169738

[1000 rows x 5 columns]

In [12]:
x = df.iloc[:,0:4].values
x

array([[3232,    3,    2,   27],
       [3107,    4,    3,   14],
       [2153,    1,    2,   32],
       ...,
       [1042,    3,    1,   11],
       [2299,    2,    2,   35],
       [ 739,    3,    3,   25]], dtype=int64)

In [14]:
y = df.iloc[:,4].values
y

array([ 682777.1502732 ,  712702.67202536,  442952.28818533,
        766553.09852794,  475021.30331083,  823664.42419755,
        733329.08568288,  406739.67394588,  650958.74821892,
        596391.54433814,  619007.90703354,  717302.25420447,
        487608.68752916,  313544.91490139,  746008.34643617,
        538844.9025289 ,  542587.80492346,  473635.27685138,
        603837.67302005,  300426.61910122,  560094.09497192,
        389925.68021422,  391320.37472948,  350601.7343873 ,
        786087.58183773,  320196.08917293,  769651.71781153,
        621338.02141692,  292630.82888217,  307870.4081703 ,
        571321.76975588,  299908.73679736,  665315.48530643,
        863804.7196924 ,  667606.0179132 ,  496859.69850035,
        294945.69561381,  661928.29768274,  569095.62340509,
        535444.19192262,  828036.34167814,  799275.41403319,
        435735.3390246 ,  918261.84882583,  888338.77530236,
        540408.0573746 ,  693617.61012268,  885349.40549827,
        865035.8513625 ,

In [17]:
from sklearn.preprocessing import LabelEncoder

In [19]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([630, 677, 272, 755, 309, 843, 705, 211, 580, 489, 525, 684, 325,
        91, 730, 400, 412, 306, 503,  67, 435, 193, 195, 141, 783, 101,
       761, 531,  55,  80, 455,  65, 604, 908, 608, 332,  60, 603, 452,
       394, 853, 807, 255, 966, 939, 405, 649, 935, 911, 877, 573, 847,
       661,  53, 946, 585, 593, 368, 565, 561, 936, 421, 952, 310, 155,
       813, 206, 417, 798, 522, 653, 970,  84, 337, 371, 788,  61, 927,
       334, 148, 560, 391, 219, 983, 432, 732,  34, 549, 638, 738, 854,
       107, 430, 476, 918, 500, 940, 558,  26, 227, 120, 223, 416, 584,
       165, 229,  92, 642, 634, 635, 944, 330,  20, 538, 913, 481, 647,
       863, 758, 437, 409, 792, 617, 294,  45, 389, 207, 393, 574, 276,
       532, 376, 331, 591, 140, 537, 126, 357, 344, 237, 528, 856, 116,
       916, 756, 958, 414, 665,  89,  10, 896, 704, 590, 335, 992, 773,
       637, 597, 187, 819, 209, 176, 851, 233, 667,  86, 959, 250, 621,
       569, 114, 747, 459, 962, 833, 192, 373, 535, 735, 876,  7

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2) 

In [26]:
x_train.size

3200

In [28]:
y_train.size

800

In [29]:
x_test.size

800

In [30]:
y_test.size

200

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\dhruv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [34]:
y_pred = logmodel.predict(x_test)
y_pred

array([907, 565, 512, 204, 970,  58, 962, 970, 225, 397, 824, 919, 994,
       680, 970, 970, 369, 397, 970, 999, 907, 945, 843, 982, 937, 966,
       970, 204, 880, 512, 919, 738, 952, 919,   8, 970, 779, 880, 992,
       565, 987, 687, 369, 823, 982, 992, 966, 204, 982, 204, 357, 512,
       997, 945, 999, 997, 880, 369, 982, 982, 999, 937, 966, 994,  58,
       945, 757, 843, 204, 994, 880, 204, 510, 993, 204, 994,  51, 880,
       204, 952, 757,  96, 757, 997, 757, 952, 982, 999, 225, 340, 512,
       397, 997, 204, 999, 757, 962, 987, 970, 856, 919, 982, 982, 987,
       843, 945, 880, 582, 982, 993, 982, 999, 106, 907, 824, 357, 843,
       994, 999, 680, 582, 824, 340,   8, 537,  58, 204, 907, 999, 937,
       919, 738, 512, 757, 956, 970, 982, 193, 824, 204, 919, 980,   8,
       966, 937, 956, 987, 369, 512, 994, 970, 945, 369, 993, 997, 910,
        58, 919, 970, 962, 972, 512, 972, 937, 371, 907, 981, 945, 369,
       865, 919, 999, 990, 945, 204, 993, 987, 880, 757, 824, 91

In [35]:
np.sort(y_pred)

array([  8,   8,   8,  51,  58,  58,  58,  58,  96, 106, 193, 204, 204,
       204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 225, 225,
       340, 340, 357, 357, 369, 369, 369, 369, 369, 369, 371, 397, 397,
       397, 397, 510, 512, 512, 512, 512, 512, 512, 512, 512, 537, 565,
       565, 582, 582, 680, 680, 687, 687, 738, 738, 757, 757, 757, 757,
       757, 757, 757, 779, 823, 823, 824, 824, 824, 824, 824, 843, 843,
       843, 843, 843, 856, 865, 880, 880, 880, 880, 880, 880, 880, 880,
       880, 907, 907, 907, 907, 907, 907, 907, 910, 910, 919, 919, 919,
       919, 919, 919, 919, 919, 919, 937, 937, 937, 937, 937, 945, 945,
       945, 945, 945, 945, 945, 945, 952, 952, 952, 956, 956, 962, 962,
       962, 962, 966, 966, 966, 966, 970, 970, 970, 970, 970, 970, 970,
       970, 970, 970, 970, 970, 972, 972, 980, 981, 982, 982, 982, 982,
       982, 982, 982, 982, 982, 982, 982, 987, 987, 987, 987, 987, 990,
       990, 992, 992, 993, 993, 993, 993, 993, 994, 994, 994, 99

In [36]:
y_test


array([522, 200, 391,  32, 517, 116, 917, 985,  82, 267, 239, 394, 504,
       395, 813, 609, 213, 164, 863, 408, 672, 808, 770, 287, 895, 226,
       877,  41, 509, 215, 986, 400, 740, 489,  21, 427, 477, 502, 384,
       624, 255, 319, 280, 428, 673, 568, 898,  44, 933,  60,  78,  87,
       971, 816, 689, 694, 619, 108,  39, 798, 596, 774, 915, 886, 119,
       712, 390, 651,  49, 328, 613, 195,  38, 900,  59, 611,  19, 663,
       170, 861, 481,  37, 530, 472,  17, 762, 978, 553, 121, 285, 452,
         9, 726,  15, 528, 456, 927, 129, 850, 320, 930, 656, 864,  54,
       827, 338, 691,  20, 717, 875, 460, 173,  26, 949, 539, 131, 529,
       769, 647, 479,  73, 430, 141,   5,  23,  89,  34, 745, 731, 791,
       376, 524, 156, 261, 402, 350, 809,  68, 703, 176, 894, 594,  10,
       612, 649, 386, 570, 107, 403, 733, 753, 835, 174, 891, 847, 896,
       189, 922, 871, 768, 848, 152, 935, 926,  64, 819, 958, 983, 250,
       257, 834, 388, 420, 870, 118, 948, 829, 749, 181, 542, 84

In [37]:
np.sort(y_test)

array([  5,   9,  10,  15,  17,  19,  20,  21,  23,  26,  32,  34,  37,
        38,  39,  41,  44,  49,  54,  59,  60,  64,  68,  73,  78,  82,
        87,  89, 101, 107, 108, 116, 118, 119, 121, 129, 131, 141, 152,
       156, 158, 164, 170, 173, 174, 176, 181, 187, 189, 195, 200, 213,
       215, 226, 239, 250, 255, 257, 261, 267, 271, 280, 285, 287, 288,
       290, 319, 320, 328, 338, 350, 376, 384, 386, 388, 390, 391, 394,
       395, 400, 402, 403, 408, 420, 427, 428, 430, 452, 456, 460, 472,
       477, 479, 481, 489, 502, 504, 509, 517, 522, 524, 528, 529, 530,
       535, 539, 540, 542, 544, 553, 568, 570, 593, 594, 596, 609, 611,
       612, 613, 619, 624, 636, 641, 647, 649, 651, 656, 663, 672, 673,
       689, 690, 691, 694, 699, 703, 712, 717, 718, 726, 731, 733, 740,
       745, 749, 753, 762, 768, 769, 770, 774, 791, 798, 808, 809, 813,
       816, 819, 827, 829, 833, 834, 835, 846, 847, 848, 850, 861, 863,
       864, 870, 871, 875, 877, 886, 891, 894, 895, 896, 898, 90

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix(y_test,y_pred)

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
(28/30)*100

93.33333333333333

In [41]:
logmodel.score(x_test,y_test)

0.0

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
classifier_knn = KNeighborsClassifier(n_neighbors=5,metric = 'minkowski' , p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [46]:
y_pred_knn = classifier_knn.predict(x_test)
y_pred_knn

array([543, 135, 312,  50, 398,  74, 760, 910,  42, 202, 206, 334, 334,
       364, 797, 527, 214,  71, 713, 299, 688, 657, 803, 313, 779, 206,
       862,  30, 488, 266, 919, 364, 784, 459,   2, 312, 527, 378, 281,
       463, 143, 276, 204, 334, 531, 334, 837,  14, 803,  86,  31,  91,
       893, 803, 446, 644, 505,  31,  84, 642, 519, 780, 803, 764,  50,
       709, 355, 652,  16, 224, 531,  86,  14, 851,  53, 478,  42, 505,
        30, 760, 364,  36, 398, 429,  74, 710, 916, 455,  53, 201, 364,
         6, 635,  14, 450, 307, 803,  84, 760, 178, 918, 658, 852,  42,
       822, 305, 661,  56, 543, 666, 335, 124,  14, 910, 476,  53, 490,
       635, 514, 462,  81, 340, 136,   0,   2,  74,   4, 648, 616, 702,
       392, 463, 124,  71, 412, 241, 707,  31, 643, 111, 947, 475,  27,
       514, 626, 335, 398, 135, 303, 532, 710, 797, 135, 764, 825, 779,
       114, 851, 822, 626, 811, 236, 910, 916,   0, 830, 837, 988, 155,
       161, 839, 308, 311, 763,  72, 860, 642, 648,  76, 490, 84

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
confusion_matrix(y_test,y_pred_knn)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
classifier_knn.score(x_test,y_test)

0.0

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(y_pred_knn,y_test)

0.0

In [53]:
from sklearn.naive_bayes import GaussianNB

In [54]:
classifer_np = GaussianNB()

In [55]:
classifer_np.fit(x_train,y_train)

GaussianNB()

In [57]:
y_pred = classifer_np.predict(x_test)
y_pred

array([543, 207, 449,  50, 459, 171, 923, 910, 120, 251, 298, 465, 365,
       480, 822, 527, 297,  71, 908, 433, 821, 693, 857, 359, 914, 253,
       862, 166, 555, 349, 959, 507, 824, 495,  45, 315, 576, 455, 422,
       498, 242, 276, 264, 396, 543, 365, 979,  63, 899, 139,  31, 163,
       979, 836, 446, 701, 505, 125,  84, 642, 519, 923, 901, 832, 157,
       783, 355, 686,  30, 246, 531, 111,  43, 920, 110, 560, 120, 505,
       194, 905, 431,  46, 507, 464,  94, 710, 918, 590, 104, 244, 480,
        35, 739,  14, 508, 453, 815,  91, 805, 292, 968, 683, 887,  42,
       881, 305, 661, 103, 607, 771, 335, 248,  14, 955, 637, 190, 490,
       635, 572, 585, 140, 434, 169,   7,  85, 171, 113, 711, 682, 702,
       392, 498, 260, 124, 461, 417, 853,  63, 643, 229, 954, 590,  45,
       669, 683, 335, 573, 182, 397, 614, 856, 921, 196, 807, 906, 779,
       218, 920, 822, 701, 913, 251, 976, 924,   0, 947, 979, 989, 332,
       161, 897, 347, 438, 763,  72, 929, 757, 823, 151, 548, 84

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.0

In [59]:
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [62]:
classifer_np.score(x_test,y_test)

0.0