In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('binance-coin.csv')
df

Date       Open       High        Low      Close       Volume  \
0     2020-12-12  27.360000  28.240000  27.330000  28.160000  238973887.0   
1     2020-12-11  27.700000  27.740000  26.770000  27.360000  278060132.0   
2     2020-12-10  28.130000  28.240000  27.430000  27.700000  263890750.0   
3     2020-12-09  27.640000  28.380000  27.000000  28.130000  323390504.0   
4     2020-12-08  29.380000  29.490000  27.510000  27.640000  323672206.0   
...          ...        ...        ...        ...        ...          ...   
1232  2017-07-29   0.104782   0.111264   0.101108   0.107811     340218.0   
1233  2017-07-28   0.107632   0.109019   0.101473   0.104067     342568.0   
1234  2017-07-27   0.105108   0.108479   0.100888   0.107737     344499.0   
1235  2017-07-26   0.105893   0.109013   0.099266   0.105138     200395.0   
1236  2017-07-25   0.115203   0.115841   0.101531   0.105870     145269.0   

        Market Cap  
0     4.067131e+09  
1     3.951108e+09  
2     3.999512e+09  
3     4.062056e+09  
4     3.990864e+09  
...            ...  
1232  1.078110e+07  
1233  1.040670e+07  
1234  1.077370e+07  
1235  1.051380e+07  
1236  1.058700e+07  

[1237 rows x 7 columns]

In [5]:
x = df.iloc[:,1:6].values
x

array([[2.73600000e+01, 2.82400000e+01, 2.73300000e+01, 2.81600000e+01,
        2.38973887e+08],
       [2.77000000e+01, 2.77400000e+01, 2.67700000e+01, 2.73600000e+01,
        2.78060132e+08],
       [2.81300000e+01, 2.82400000e+01, 2.74300000e+01, 2.77000000e+01,
        2.63890750e+08],
       ...,
       [1.05108000e-01, 1.08479000e-01, 1.00888000e-01, 1.07737000e-01,
        3.44499000e+05],
       [1.05893000e-01, 1.09013000e-01, 9.92660000e-02, 1.05138000e-01,
        2.00395000e+05],
       [1.15203000e-01, 1.15841000e-01, 1.01531000e-01, 1.05870000e-01,
        1.45269000e+05]])

In [6]:
y = df.iloc[:,6].values
y

array([4.06713146e+09, 3.95110842e+09, 3.99951156e+09, ...,
       1.07737000e+07, 1.05138000e+07, 1.05870000e+07])

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1084, 1057, 1067, ...,    9,    4,    5], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2) 

In [11]:
x_train.size

4945

In [12]:
y_train.size

989

In [13]:
x_test.size

1240

In [14]:
y_test.size

248

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\dhruv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
y_pred = logmodel.predict(x_test)
y_pred

array([1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 11

In [18]:
np.sort(y_pred)

array([1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171, 1171,
       1171, 1171, 1171, 1171, 1171, 1171, 1171, 11

In [19]:
y_test


array([ 870,  618, 1208,  991,  436,  721,  120,  621,  452, 1043,  166,
        880,  239,  795,  177,  208, 1078,  770, 1217,  933,   12,  350,
        942,  776,  710,   98,  157,  543,  322,    6,  318, 1123, 1149,
         96,   82,  268,  790,  748,   92,  800,  832,  481,  582,  233,
        648,  495,  382,  778,  227,  265,   17,  398,   46,  500,  704,
        175,  868,  974,  230,  707,  203,  413,  478,  244,  314,  102,
        992,  631,  246, 1037,  381,  760, 1127,  466,  348,   74, 1125,
        127,  125,   38, 1190,  831,  326,  587, 1044,  813,  567,  446,
       1182,  653,  357,  458,  569,  251,  399,  222,  215,  223,  817,
        850,  807,  317, 1153,  335,  394, 1012,  511,  393,  949, 1126,
        784,  787, 1121,  592,  291,   24,  768,  657,  533,  354,  906,
        890,  851, 1093,  894, 1062,  482,    1,  629,  888,  294,  186,
        198,  686,  765,  775,  764, 1033, 1084, 1144,  896,  698,  915,
         67, 1147,  306,  135,  579,  279, 1013,  8

In [20]:
np.sort(y_test)

array([   1,    6,   12,   17,   24,   27,   28,   38,   42,   46,   67,
         74,   79,   82,   86,   92,   96,   98,  102,  111,  120,  125,
        127,  134,  135,  136,  137,  146,  157,  162,  165,  166,  170,
        175,  177,  183,  186,  196,  198,  203,  208,  212,  215,  222,
        223,  227,  229,  230,  233,  239,  244,  246,  251,  265,  268,
        272,  279,  286,  288,  291,  294,  296,  302,  304,  306,  314,
        317,  318,  319,  322,  325,  326,  335,  347,  348,  350,  354,
        357,  368,  377,  379,  381,  382,  393,  394,  395,  398,  399,
        402,  407,  413,  416,  420,  421,  429,  436,  446,  452,  453,
        454,  458,  463,  466,  478,  481,  482,  486,  495,  500,  511,
        518,  524,  528,  533,  543,  567,  569,  579,  582,  587,  589,
        590,  592,  608,  612,  615,  618,  621,  628,  629,  631,  642,
        646,  647,  648,  653,  657,  686,  698,  703,  704,  707,  710,
        721,  733,  741,  745,  747,  748,  760,  7

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
(28/30)*100

93.33333333333333

In [24]:
logmodel.score(x_test,y_test)

0.0

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
classifier_knn = KNeighborsClassifier(n_neighbors=5,metric = 'minkowski' , p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
y_pred_knn = classifier_knn.predict(x_test)
y_pred_knn

array([ 884,  603,  772,  755,  243,  439,   40,  680,  607,  661,  113,
        722,  234,  848,   93,  121,  934,  625,  654,  667,    0,  112,
       1082,  571,  914,   39,  103,  283,   30,    0,  114,  750,  697,
         72,   18,  603,  521,  519,   39, 1087,  772,  243,  131,  210,
        667,  231,  108,  637,  119,   97,   16,  114,   23,  674,  609,
         97,  624,  573,  106,  684,  199,  200,  334,  126,   91,   35,
        805,  762,  249, 1032,  187,  410,  620,  614,  123,   15,  424,
        108,  236,   18,  680,  847,  299,  649, 1051,  681,  457,  424,
        672,  638,  428,  192,  598,  151,  126,  106,   60,  150,  843,
        601,  469,  236,  702,  346,   41,  588,  470,  138,  779,  571,
        762,  843,  457,  619,  140,   23,  517,  627,  192,  470,  614,
        743,  580,  588,  759,  822,  336,    0,  247,  855,  167,  346,
        126,  601,  753,  929,  622,  674,  871,  762,  669,  365,  929,
         43,  602,  252,  119,  310,  113,  908,  9

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test,y_pred_knn)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
classifier_knn.score(x_test,y_test)

0.0

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y_pred_knn,y_test)

0.0

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
classifer_np = GaussianNB()

In [35]:
classifer_np.fit(x_train,y_train)

GaussianNB()

In [36]:
y_pred = classifer_np.predict(x_test)
y_pred

array([ 884,  738, 1057, 1079,  447,  560,  189,  766,  861,  833,  160,
        931,  516,  873,   93,  121, 1163,  917, 1056,  667,    9,  316,
       1100,  571, 1188,   78,  156,  435,  159,    3,  332,  750,  697,
        390,   18,  736,  593,  887,   39, 1087, 1057,  376,  131,  210,
        879,  250,  340,  637,  182,  155,   49,  254,   63,  674,  948,
         97,  624,  617,  106,  684,  266,  333,  334,  383,  220,   35,
        971,  762,  508, 1072,  285,  925,  668,  774,  367,   34,  719,
        341,  236,   18,  766,  892,  510, 1133, 1187,  681,  705,  719,
        672,  797,  472,  192,  684,  151,  297,  106,  129,  438,  986,
       1028,  883,  236, 1110,  369,  163,  988,  529,  321,  854,  571,
       1017,  986,  705, 1152,  187,   47, 1202,  630,  386,  470,  774,
       1212,  864,  788, 1085,  822,  423,    3,  247, 1001,  442,  369,
        409, 1028, 1096, 1223,  625,  891, 1122, 1065,  669,  613, 1223,
         51,  602,  252,  295,  310,  113, 1222, 11

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.0

In [38]:
confusion_matrix(y_test,y_pred)

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
classifer_np.score(x_test,y_test)

0.0